# ============================
# Build config para Nuxt 3 SSR en Netlify
# ============================

[build]
  command = "npm run build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--legacy-peer-deps"
