# ============================
# Build config para Nuxt 3 SSR en Netlify
# ============================

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--legacy-peer-deps"
  SECRETS_SCAN_ENABLED = "false"
